### ISSUE TITLE
ufo-query more verbose output

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#104]
This is already useful but would it be possible to get the full property description with type and help message?

**Comment by matze** [comment]
Definitely would be possible. Sole reason it is like this is now, is for the bash completion script of [ufo-launch](https://github.com/ufo-kit/ufo-core/blob/master/bin/ufo-launch).

**Comment by tfarago** [comment]
:+1:

**Comment by evoliptic** [comment]
Hey matze!


how are you?


As i got some mails from github about ufo-core, i'm curious : how is it going about directgma? did you got some results at the end, with the help from amd?


does the team still plan to go to paris? if yes, let me be aware!


salute everybody from me : lorenzo, andreas, suren, and such!

tchuss!




________________________________
De : Matthias Vogelgesang <notifications@github.com>
Envoyé : mercredi 23 mars 2016 14:27
À : ufo-kit/ufo-core
Objet : Re: [ufo-core] ufo-query more verbose output (#104)


Definitely would be possible. Sole reason it is like this is now, is for the bash completion script of ufo-launch<https://github.com/ufo-kit/ufo-core/blob/master/bin/ufo-launch>.

-

**Comment by matze** [comment]
Interesting way of getting in contact with me ;-)

The firmware is still moving and changing so we are still developing the code but on the upside we got the NDA signed, so we can ask AMD about problems we think might stem from their OpenCL implementation. But we do not develop the code in the open anymore, because it's really only useful for us (anyone else would need our hardware and firmware anyway to work).
