### ISSUE TITLE
Preparation for Debian package

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#111]
This issue tracks everything required for proper Debian packaging:

- [x] fix #109: build manpages
- [x] check systemd service file installation
- [x] tell @picca to use and test `-DINSTALL_COMPLETION=ON`
- [x] release version 0.11.1

**Comment by matze** [comment]
@picca: could you check if enabling `INSTALL_COMPLETION` compiles, installs and works? It should complete plugins and parameters for `ufo-launch`.

**Comment by picca** [comment]
I am on it :).

can you add also the .service files installation ?

this way I will be able to create a serice file.
I have only once concern, it that it would be nice to be able to configure the listening port via an /etc/ufodrc or something simillar.

but maybe I am wrong. I should see ow otherpackages are doing. In fact what is the proper way to gives parameters to a daemon the systemd way ?

**Comment by matze** [comment]
Yeah, besides a configuration file I can only think of environment variables to control such parameters.

**Comment by picca** [comment]
I found this an d yes it seems that the environment variableis the way to go :)

https://patrakov.blogspot.fr/2011/01/writing-systemd-service-files.html

**Comment by matze** [comment]
I made a branch and accompanying [PR](https://github.com/ufo-kit/ufo-core/pull/112) that tries to install `ufod.service` the correct way. Unfortunately, I cannot check this right now on my laptop but it "should" work ;-)

**Comment by picca** [comment]
Hello, I installed libsystemd-dev package but when I build it I get this error

-- Checking for module 'systemd'
--   No package 'systemd' found
-- Configuring done
-- Generating done

**Comment by picca** [comment]
the file available in libsystemd-dev is

/usr/lib/i386-linux-gnu/pkgconfig/libsystemd.pc

which contains

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/i386-linux-gnu
includedir=/usr/include

Name: systemd
Description: systemd Library
URL: http://www.freedesktop.org/wiki/Software/systemd
Version: 232
Libs: -L${libdir} -lsystemd
Cflags: -I${includedir}

no reference to the service filespath..., maybe this is the wrong package

**Comment by picca** [comment]
Ok, I found a systemd.pc in the systemd package, lets see

**Comment by picca** [comment]
Just for reference

https://wiki.debian.org/Teams/pkg-systemd/Packaging

**Comment by picca** [comment]
It works ;),now we just need to have this /etc/default/ufod mecanism in order to configure ufod parameters :))


Cheers

drwxr-xr-x root/root         0 2013-11-11 08:07 ./
drwxr-xr-x root/root         0 2013-11-11 08:07 ./lib/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./lib/systemd/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./lib/systemd/system/
-rw-r--r-- root/root       111 2013-11-11 08:07 ./lib/systemd/system/ufod.service
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/bin/
-rwxr-xr-x root/root      9752 2013-11-11 08:07 ./usr/bin/ufod
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/share/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/share/doc/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/share/doc/ufod/
-rw-r--r-- root/root       168 2013-11-11 08:07 ./usr/share/doc/ufod/changelog.Debian.gz
-rw-r--r-- root/root      1260 2013-11-11 08:07 ./usr/share/doc/ufod/copyright
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/share/man/
drwxr-xr-x root/root         0 2013-11-11 08:07 ./usr/share/man/man1/
-rw-r--r-- root/root       616 2013-11-11 08:07 ./usr/share/man/man1/ufod.1.gz

**Comment by matze** [comment]
I don't think we need `/etc/default/ufod` as I wrote in my earlier comment and as also stated by the Debian packaging documentation itself:

> Note that it is preferable to configure options using native systemd mechanisms for new packages, the above is only for backwards compatibility. New packages should advise their users to override the ExecStart line by dropping a file like this in /etc/systemd/system/foo.service.d/local.conf: 

I will merge the branch now. If you have anymore points that need to be done for the Debian packaging please let me know. By the way, you want me to include your changes to the `control` file?

**Comment by picca** [comment]
Yes I ed this part also and I will need to find a way for the user to selectionne the port during the installation.

let's release and upload now :)

Once released, I will see how to update the debian directory with the official package.

**Comment by matze** [comment]
Tag is pushed, release is out, this issue is closed ;-)
