### ISSUE TITLE
How about merging ufo-core and ufo-filters?

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/ufo-core#181]
From time to time I find it a bit complicated to test things and putting ufo-core and ufo-filters together would make such things more easy.

Pro:
I think nobody uses only one of ufo-core and ufo-filters.
Would make tests (and bigger changes) easier to implement, since one must not make sure that both versions match,

Con:
Splitting both makes sense to keep everything clean.

Open for discussion.

Best,
Marcus

**Comment by tfarago** [comment]
I have often wished it was like this for practical reasons. Having the two always felt a bit artificial because there is no way one can use filters without core. On the other hand, one *can* just take the core a write their own set of filters and who knows, perhaps on the dark side of the moon there is someone harnessing the power of the core with their own proprietary top-secret filters... On the third other hand, yes right 😉 ...
So, I don't know. What I do know is that I don't want to rewrite the cmake and meson scripts 😅

**Comment by matze** [comment]
Not sure what happened but it used to be [one repo](https://github.com/ufo-kit/ufo-core/commit/af26f56). History is cloudy but it could be because of packaging for Debian. But again, I am not sure.

**Comment by tfarago** [comment]
Oh cool, we can check how smart `git revert` is 😄

**Comment by MarcusZuber** [comment]
Maybe I will add a PR and try how ugly it will be...

**Comment by llohse** [comment]
I realize that this is probably an internal discussion but I leave my two cents regardless.

To me as an outsider, merging the filters into core sounds very reasonable. This would also likely fix #182, because the tests can be run prior to installation.

You could easily make ufo-filters an optional module of ufo that can be deselected with a cmake/meson option. That way, if somebody really wants to, they can install the bare ufo-core. This also should not require that much rewriting of the cmake/meson scripts. Ideally you can just drop the in the subdirectory, remove a little bit and include them from the top level script.

**Comment by MarcusZuber** [comment]
I'm also favouring to put both together. Making the filters selectable with cmake/meson options is a good suggestion.

I will try puth the things together in the next days, so we can give it a try.

@matze Are you still in contact with Picca Frédéric-Emmanuel?

**Comment by matze** [comment]
I am not anymore but @picca is around here as well ;-)

**Comment by MarcusZuber** [comment]
I just dumped everything into https://github.com/ufo-kit/ufo-core/pull/186 (without much manual work and deep thinking).
At least build with cmake seams to work...
